from datetime import datetime

from src.models.fits_models.abstract_fits import FitsInfoAbstract


class FitsInfoAndor(FitsInfoAbstract):
    def __init__(self, info):
        self.SIMPLE = info[0]
        self.BITPIX = info[1]
        self.NAXIS = info[2]
        self.NAXIS1 = info[3]
        self.NAXIS2 = info[4]
        self.NAXIS3 = info[5]
        self.EXTEND = info[6]
        self.HEAD = info[7]
        self.ACQMODE = info[8]
        self.READMODE = info[9]
        self.IMGRECT = info[10]
        self.HBIN = info[11]
        self.VBIN = info[12]
        self.SUBRECT = info[13]
        self.DATATYPE = info[14]
        self.XTYPE = info[15]
        self.XUNIT = info[16]
        self.RAYWAVE = info[17]
        self.CALBWVNM = info[18]
        self.TRIGGER = info[19]
        self.CALIB = info[20]
        self.DLLVER = info[21]
        self.EXPOSURE = info[22]
        self.TEMP = info[23]
        self.READTIME = info[24]
        self.OPERATN = info[25]
        self.GAIN = info[26]
        self.EMREALGN = info[27]
        self.VCLKAMP = info[28]
        self.VSHIFT = info[29]
        self.PREAMP = info[30]
        self.SERNO = info[31]
        self.UNSTTEMP = info[32]
        self.BLCLAMP = info[33]
        self.PRECAN = info[34]
        self.FLIPX = info[35]
        self.FLIPY = info[36]
        self.CNTCVTMD = info[37]
        self.CNTCVT = info[38]
        self.DTNWLGTH = info[39]
        self.SNTVTY = info[40]
        self.SPSNFLTR = info[41]
        self.THRSHLD = info[42]
        self.PCNTENLD = info[43]
        self.NSETHSLD = info[44]
        self.PTNTHLD1 = info[45]
        self.PTNTHLD2 = info[46]
        self.PTNTHLD3 = info[47]
        self.PTNTHLD4 = info[48]
        self.AVGFTRMD = info[49]
        self.AVGFCTR = info[50]
        self.FRMCNT = info[51]
        self.PORTMODE = info[52]
        self.LSHEIGHT = info[53]
        self.LSSPEED = info[54]
        self.LSALTDIR = info[55]
        self.LSCTRL = info[56]
        self.LSDIR = info[57]
        self.FKSMODE = info[58]
        self.FKTMODE = info[59]
        self.USERTXT1 = info[60]
        self.USERTXT2 = info[61]
        self.USERTXT3 = info[62]
        self.USERTXT4 = info[63]
        self.EXPOTIME = info[66]
        self.FRAME = info[67]
        self.ESHTMODE = info[68]
        self.HIERARCH_PREAMPGAINTEXT = info[69]
        self.HIERARCH_SPECTROGRAPHSERIAL = info[70]
        self.HIERARCH_SHAMROCKISACTIVE = info[69]
        self.HIERARCH_SPECTROGRAPHNAME = info[70]
        self.HIERARCH_SPECTROGRAPHISACTIVE = info[71]

    def get_norm_time(self):
        time = self.EXPOTIME
        return time[-8:]

    def get_datetime(self):
        date = str(self.EXPOTIME)
        return datetime(int(date[:4]), int(date[5: 7]), int(date[8: 10]),
                                 int(date[11: 13]), int(date[14: 16]), int(date[17: 20]))

